# Meta Data for SEO

## Homepage
title = "Owncast"
titleSeparator = "-"
titleAddition = "Selfhosted Livestreaming"
description = "Owncast is a self-hosted live video and web chat server for use with existing broadcasting software. Point your live stream at a Owncast server you personally control and regain ownership over your content."

## Open Graph + Twitter Cards
images = ["/images/owncast-logo-1000x1000.png"]
twitterSite = "owncastlive"
twitterCreator = "owncastlive"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "/images/owncast-logo-1000x1000.png"
schemaGitHub = "https://github.com/owncast"
schemaTwitter = "https://twitter.com/owncastlive"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Created by FOSS-loving people around the globe. Website based on <a href=\"https://getdoks.org/\">Doks</a>."

# Alert
alert = false
alertText = "The Owncast project is offering free instances to those that could use them. <a class=\"alert-link\" href=\"/donated/\">Learn more!</a></a>"

# Edit Page
docsRepo = "https://github.com/owncast/owncast.github.io"
editPage = false
